### ISSUE TITLE
Error: Request failed with status code 406

### ISSUE THREAD

**Issue by liuxi653** [hastic/hastic-server#605] opened 2019-04-25 09:50 UTC
hi,all
    i use hastic032 to label data, but it will return 406, Have you ever encountered a 406 error? is it a ts problem or python problem?
![image](https://user-images.githubusercontent.com/37133475/56726242-f5462300-6780-11e9-81e0-80deb887b696.png)

![image](https://user-images.githubusercontent.com/37133475/56726266-02631200-6781-11e9-94ef-9f12dbace36a.png)

![image](https://user-images.githubusercontent.com/37133475/56726277-0858f300-6781-11e9-892f-1b23ebb4b6e3.png)

![image](https://user-images.githubusercontent.com/37133475/56726321-1b6bc300-6781-11e9-8622-3e32f11de274.png)

![image](https://user-images.githubusercontent.com/37133475/56726374-2f172980-6781-11e9-8dc5-791be0c03eed.png)

![image](https://user-images.githubusercontent.com/37133475/56726389-36d6ce00-6781-11e9-9a8c-66dcbf141e78.png)

**Comment by jonyrock** [comment] 2019-04-25 13:02
@amper43 we need to add details of this 406 error: where it happened and what Grafana / datasource returned if it caused by grafana / datasource or whatever

**Comment by jonyrock** [comment] 2019-04-25 13:15
@liuxi653 add please "metric" tab and "hastic info" tab

**Comment by liuxi653** [comment] 2019-04-30 05:51
hi, sorry for the late reply.
metric:
![image](https://user-images.githubusercontent.com/37133475/56942710-a61c3b80-6b4e-11e9-9789-a9e32c3346e6.png)

hastic info
![image](https://user-images.githubusercontent.com/37133475/56942718-b2a09400-6b4e-11e9-9377-4c073ca91d9a.png)

datasource
![image](https://user-images.githubusercontent.com/37133475/56942725-bcc29280-6b4e-11e9-9e6f-ca01d6a1aa33.png)

node version
![image](https://user-images.githubusercontent.com/37133475/56942734-ca781800-6b4e-11e9-923c-ec846390ac62.png)

system info
centos7.4

**Comment by rozetko** [comment] 2019-04-30 12:48
Hi, @liuxi653 
I need both Grafana and hastic-server logs appearing when you get this error. Can you help me with that, please?

You can get them by following steps:
hastic-server logs:
- if you've installed it from `.tar.gz` / RPM / source: they can be seen in the terminal where you run `grafana-server` 
- If you've installed it via docker-compose: `docker-compose logs` in hastic-server directory

Grafana logs:
- if you've installed Grafana via RPM: `journalctl -u grafana-server` 
- if you've installed it from `.tar.gz`: they can be seen in the terminal where you run `grafana-server`

**Comment by rozetko** [comment] 2019-04-30 12:55
The reason for this error might be system language / encoding
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406
![image](https://user-images.githubusercontent.com/1989898/56962634-bbe62c80-6b5f-11e9-933b-10a6a3de9bf0.png)

**Comment by liuxi653** [comment] 2019-05-05 07:26
> Hi, @liuxi653
> I need both Grafana and hastic-server logs appearing when you get this error. Can you help me with that, please?
> 
> You can get them by following steps:
> hastic-server logs:
> 
> * if you've installed it from `.tar.gz` / RPM / source: they can be seen in the terminal where you run `grafana-server`
> * If you've installed it via docker-compose: `docker-compose logs` in hastic-server directory
> 
> Grafana logs:
> 
> * if you've installed Grafana via RPM: `journalctl -u grafana-server`
> * if you've installed it from `.tar.gz`: they can be seen in the terminal where you run `grafana-server`

hi,rozetko
    below is hastic-server log
![image](https://user-images.githubusercontent.com/37133475/57190146-e3673b80-6f49-11e9-9e3e-c1e4773c55d7.png)

  i will upload grafana-server log later

**Comment by liuxi653** [comment] 2019-05-05 07:46
> The reason for this error might be system language / encoding
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406
> ![image](https://user-images.githubusercontent.com/1989898/56962634-bbe62c80-6b5f-11e9-933b-10a6a3de9bf0.png)

I've tried to change LANG to en_US.UTF-8,but it didn't work.

**Comment by rozetko** [comment] 2019-05-07 11:41
We should log more info about datasource-request error to understand the reason of this problem
We will fix it in #494 soon

**Comment by jonyrock** [comment] 2019-05-24 05:38
Hey @liuxi653 , please try new 0.3.4 version. We added better logging to these kind of errors.

**Comment by amper43** [comment] 2019-06-06 18:50
This issue will be fixed by:
https://github.com/CorpGlory/grafana-datasource-kit/issues/71
https://github.com/CorpGlory/grafana-datasource-kit/issues/72

**Comment by rozetko** [comment] 2019-06-18 13:41
Fixed via https://github.com/hastic/hastic-server/commit/387445a54613662ad9ec6525fbfa1eee9c1d4dd1

**Closed by rozetko** 2019-06-18 13:41 UTC
Labels: !, bug, server

**Comment by jonyrock** [comment] 2019-07-14 20:43
https://github.com/CorpGlory/grafana-datasource-kit/issues/71
